### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by pwaller**
* Update poppler-0.60.1 and openjpeg-master
  Note: poppler has had major surgery: [`9773c1534668d84b8267c3e5c9d612076fa231a5`](https://cgit.freedesktop.org/poppler/poppler/commit/?id=9773c1534668d84b8267c3e5c9d612076fa231a5)

  Looks in principle beneficial since it removes a lot of pointers and
  replaces them with references.

  I would have taken a tag of openjpeg, except for a minor bug:

  * https://github.com/uclouvain/openjpeg/commit/66297f07a43d2770a97c8456d20202f3d051d980

* Update fontconfig, freetype2 and Little-CMS

@ashkulz, this touches code you recently wrote for a feature we don't yet use - would you be able to test and comment before I merge this pull request?

### CODE REVIEW

**Comment by pwaller** [comment]
I've done some tests on a large internal PDF corpus. This does appear to change cause some minor output changes primarily of the path data. The sizes of all outputs for all files are identical, just that some of the coordinates have changed slightly in the path data. I currently believe this to be a minor impact, but will investigate a little further later.

**Comment by ashkulz** [comment]
Looks OK to me, will test and confirm by tomorrow.

**Comment by ashkulz** [comment]
Checked with a few sample files, looks good :+1:

**Comment by pwaller** [comment]
Excellent, thanks for your feedback. My plate is a little full, so this may not get merged for a couple of weeks, but I have got a reminder set to come back to it in the not-too-distant future.

**Pull request merged**
